version: '3'

services:
        zabbix-agent:
                restart: always
                image: zabbix/zabbix-agent:latest
                ports:
                        - "10050:10050"
                environment:    
                        ZBX_HOSTNAME: dsiZabbixServer
                        ZBX_SERVER_HOST: 10.0.0.158
